[package]
name = "awman"
version = "0.1.0"
authors = ["sebashwa <sebashwa@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.0-alpha1"



